namespace Nixill.Streaming.JoltBot.Games.UFO50;

public static class UFO50Games
{
  private static readonly string[] GameList = [
    "Library",
    "Barbuta",
    "Bug Hunter",
    "Ninpek",
    "Paint Chase",
    "Magic Garden",
    "Mortol",
    "Velgress",
    "Planet Zoldath",
    "Attactics",
    "Devilition",
    "Kick Club",
    "Avianos",
    "Mooncat",
    "Bushido Ball",
    "Block Koala",
    "Camouflage",
    "Campanella",
    "Golfaria",
    "The Big Bell Race",
    "Warptank",
    "Waldorf's Journey",
    "Porgy",
    "Onion Delivery",
    "Caramel Caramel",
    "Party House",
    "Hot Foot",
    "Divers",
    "Rail Heist",
    "Vainger",
    "Rock On! Island",
    "Pingolf",
    "Mortol II",
    "Fist Hell",
    "Overbold",
    "Campanella 2",
    "Hyper Contender",
    "Valbrace",
    "Rakshasa",
    "Star Waspir",
    "Grimstone",
    "Lords of Diskonia",
    "Night Manor",
    "Elfazar's Hat",
    "Pilot Quest",
    "Mini & Max",
    "Combatants",
    "Quibble Race",
    "Seaside Drive",
    "Campanella 3",
    "Cyber Owls"
  ];

  public static string Get(int num) => GameList[num];
}